interface Project {
  id: number;
  institute: string;
  degree: string;
  year: string;
  description: string;
}

const projectData: Project[] = [

  { id: 1, institute: "NTNU, Trondheim", degree: `n the Influence of Alzheimer's Disease on Interneural Communication via Extracellular Vesicles`, year: "Autumn 2024",
    description:`On the Influence of Alzheimer's Disease on Interneural Communication via Extracellular Vesicles}
        {}
        {Conference Paper based on my thesis, presented at NANOCOMM; Nanoscale Computing and Communication 2024,
        \n DOI: 10.1145/3686015.3689357`},


  { id: 2, institute: "NTNU, Trondheim", degree: `Sensors anomaly detection, isolation, identification for digital twins using
    model-based approach`, year: "Autumn 2022",
    description:` The main objective of this project is developing a modelbased
    framework for sensor fault detection, isolation, and identification to prevent
    the processing of corrupted sensor data. I prepared the data for the framework by
    creating a time-series of the sensor data., Supervisor: Dr. Pierluigi Salvo Rossi,
    NTNU.`},

    { id: 3, institute: "NTNU, Trondheim", degree: `Sound Level Measurement` , year: "Summer 2022",
      description: `Measuring the rating level of the sound generated by a ventilation
       exhaust of the Main building. The measurement task involved working with the sound recorder,
        microphone and calibrator. The post processing of the recorded file was done in Julia.
        `},

  { id: 4, institute: "NTNU, Trondheim", degree: "Design, build and test of a wind turbine", year: "Autumn 2021", 
    description: `As the final project of the 
    Design of The Wind Turbine Course, our team designed a 2 blades wind turbine based on the BEM 
    algorithm and it was simulated with Ashes simulation software.
    The performance of the real model was tested in the wind tunnel and the result was evaluated.`},

  { id: 5, institute: "Amirkabir University of Techonlogy (Tehran\'s Polytechnic), Tehran", degree: "Windows Application for Syncing Directories Contents,", year: "Spring 2018",
    description:
    `As the final project of the advanced programming course, my team designed a Windows-based application
    for synchronizing the contents of two given directories. It was written with C++
    and Python and the graphical features were designed with Qt., Course Professor:
    Dr. Amir Jahanshahi, Amirkabir University of Technology.`},

];


export default function ProjectSection() {
  return (
    <div className="w-full p-6 rounded-lg">
      <h2 className="text-3xl font-bold mb-4">Education</h2>
      <table className="w-full border-collapse">
        <tbody>
          {projectData.map((edu) => (
            <tr key={edu.id} className="border-b">
              <td className="p-4 text-lg">
                <p>{edu.degree}</p> 
                <p className="text-base">{edu.institute}</p>
                <p className="mt-2 text-sm text-gray-500">
                  {edu.description}
                </p>
              </td>
              <td className="p-4 text-gray-500">{edu.year}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
